### ISSUE TITLE
Importing from 'typescript-optional' does not work

### ISSUE THREAD

**Issue by andynunes** [bromne/typescript-optional#18]
Hi there! I came across your package today and think it's fantastic as a Java dev using TypeScript!

I see that you just released 2.0.0 today, just hours before I searched for this package.

I followed the README, which states to import like:
`import { Optional } from 'typescript-optional';`

However, this doesn't work, I believe because of the following lines in `package.json`:
`"main": "dist/index.js",`
and perhaps also
`"types": "dist/index.d.ts",`

When installed via npm, there is no `dist` directory, and as there is no `index.js` or `index.ts` in the root directory, nothing is imported at `typescript-optional`.

As a work-around I will be using:
`import { Optional } from 'typescript-optional/src';`
however, I wanted to make sure you see this to validate if it's a bug or if I'm missing something.

Thank, you rock!

**Comment by bromne** [comment]
Thank you for your report. I abandoned `typescript-optional@2.0.0` necessarily.
I'm going to fix the problem.

**Comment by andynunes** [comment]
Awesome, thank you @bromne !

**Comment by bromne** [comment]
`typescript-optional@2.0.1` has been released!
