### ISSUE TITLE
Returning null/undefined in mapper function causes TypeError: The passed value was null or undefined.

### ISSUE THREAD

**Issue by alexa-rbo** [bromne/typescript-optional#4]
Please consider merging my PR, this behavior is supported by the original Java implementation of Optional as you can see from its implementation:
```java
    public<U> Optional<U> map(Function<? super T, ? extends U> mapper) {
        Objects.requireNonNull(mapper);
        if (!isPresent())
            return empty();
        else {
            return Optional.ofNullable(mapper.apply(value));
        }
    }
```

**Comment by alexa-rbo** [comment]
#3

**Comment by bromne** [comment]
Thank you for you issue, I merged your pull request.
I'm sorry to be long in response.

**Comment by bromne** [comment]
updated version in npm. (1.4.0 now)

https://www.npmjs.com/package/typescript-optional
