### ISSUE TITLE
orElseThrow should be able to interrupt the application flow.

### ISSUE THREAD

**Issue by victorbarlac** [bromne/typescript-optional#44]
In some cases, `orElseThrow()` won't stop the normal flow of the application as it happens in Java, providing undefined or wrong values as return value of a method that is using `Optional`

**Comment by mgohin** [comment]
Do you have an code example ? If it does not stop your workflow it's probably not because of this lib.

**Comment by victorbarlac** [comment]
Hello! I'm not working for the company I was back then when I posted this. Also, I no longer have access to the project in which I was facing the problem and couldn't get to reproduce it again (on stackblitz or offline with Angular). So it could be just an alternative flow path I was calling from inside `orElseThrow` that kept the app running and stumbling on further problems/bugs as consequence.
Anyway, thanks!

**Comment by victorbarlac** [comment]
Hello! I'm not working for the company I was back then when I posted this. Also, I no longer have access to the project in which I was facing the problem and couldn't get to reproduce it again (on stackblitz or offline with Angular). So it could be just an alternative flow path I was calling from inside orElseThrow that kept the app running and stumbling on further problems/bugs as consequence.
Anyway, thanks!
